title: Revista Porto Alegre
email: revistaportoalegre@revistaportoalegre.com
description: Pensamento, sociedade, cultura
baseurl: ""
url: "https://italoalves93.github.io"
icon: /assets/images/icon-512.png
twitter_username: revportoalegre

markdown: kramdown
kramdown:
  footnote_nr: 1
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo

permalink: /:title/

collections:
  issues:
    output: true
    permalink: /numeros/:path/

defaults:
  - scope:
      path: ""
      type: "issues"
    values:
      layout: "issue"

paginate: 10
paginate_path: "/pag/:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - hitchens-theme.gemspec
  - screenshot.png
